### ISSUE TITLE
Add delete button to documents 

### ISSUE THREAD

**Issue by tbock** [Innovate-Inc/Experience-Builder-Widgets#5]
Delete should just delete the relationship between that record and the document.  However we should probably create a MS Flow that is triggered on deletes to check to see if a document is no long related to anything.  If document has no relationships then delete it?

**Comment by dspinosa** [comment]
ms flow issue created in JST Repo

**Comment by dlovettinnovate** [comment]
closing for this repo. Reference https://github.com/Innovate-Inc/JST/issues/48 for further work
